apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rode-collector-build.fullname" . }}
  labels:
    {{- include "rode-collector-build.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "rode-collector-build.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "rode-collector-build.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" ($.Chart.AppVersion) ) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--port={{ .Values.service.port }}"
            - "--rode-host={{ .Values.rode.host }}"
            {{- if .Values.rode.auth.proxy.enabled }}
            - "--proxy-auth"
            {{- end }}
            - "--rode-insecure-disable-transport-security={{ .Values.rode.disableTransportSecurity }}"
            - "--debug={{ .Values.debug }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- with .Values.extraEnv }}
          env:
          {{ toYaml . | indent 12 }}
          {{- end }}
          readinessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:{{ .Values.service.port }}"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:{{ .Values.service.port }}"]
            initialDelaySeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
  {{- end }}
