apiVersion: v1
kind: Service
metadata:
  name: {{ include "rode-collector-build.fullname" . }}
  labels:
  {{- include "rode-collector-build.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: rode-collector-build
  selector:
    app: {{ template "rode-collector-build.name" . }}
    release: {{ .Release.Name }}
