replicaCount: 1

image:
  repository: "ghcr.io/rode/collector-build"
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8082

debug: false

rode:
  host: rode:50051

  ## disableTransportSecurity will disable GRPC transport security when set to `true`
  ##
  disableTransportSecurity: false

  ## Rode authentication settings
  ## Use rode.auth.proxy.enabled to enable proxy auth
  ##
  auth:
    proxy:
      enabled: false

ingress:
  grpc:
    enabled: false
    annotations: {}
    hosts: []
    tls: []
  http:
    enabled: false
    annotations: {}
    hosts:
      - host: chart-example.local
        paths: []
    tls: []

resources:
  limits:
    cpu: 128m
    memory: 64Mi
  requests:
    cpu: 64m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
