{{- if and .Values.auth.oidc.enabled .Values.auth.basic.enabled }}
  {{ fail "Only one authentication method can be set" }}
{{- end }}
{{- if or .Values.auth.oidc.enabled .Values.auth.basic.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rode.fullname" . }}-auth
  labels:
    {{- include "rode.labels" . | nindent 4 }}
stringData:
  {{- if .Values.auth.oidc.enabled }}
  OIDC_ISSUER: "{{ .Values.auth.oidc.issuer }}"
  OIDC_REQUIRED_AUDIENCE: "{{ .Values.auth.oidc.requiredAudience }}"
  OIDC_ROLE_CLAIM_PATH: "{{ .Values.auth.oidc.roleClaimPath }}"
  OIDC_TLS_INSECURE_SKIP_VERIFY: "{{ .Values.auth.oidc.tlsInsecureSkipVerify }}"
  {{- end }}
  {{- if .Values.auth.basic.enabled }}
  BASIC_AUTH_USERNAME: "{{ .Values.auth.basic.username }}"
  BASIC_AUTH_PASSWORD: "{{ .Values.auth.basic.password }}"
  {{- end }}
{{- end }}
