apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rode.fullname" . }}
  labels:
    {{- include "rode.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rode.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rode.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-grafeas
          image: curlimages/curl:7.73.0
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-c"
            - |
              until curl --output /dev/null --silent --fail --max-time 2 {{ .Values.grafeas.host }}/v1beta1/projects; do sleep 1; done;
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" ($.Chart.AppVersion) ) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--port={{ .Values.service.port }}"
            - "--grafeas-host={{ .Values.grafeas.host }}"
            - "--opa-host={{ .Values.opa.host }}"
            - "--elasticsearch-host={{ .Values.elasticsearch.host }}"
            - "--debug={{ .Values.debug }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- with .Values.extraEnv }}
          env:
            {{ toYaml . | indent 12 }}
          {{- end }}
          readinessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:{{ .Values.service.port }}"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:{{ .Values.service.port }}"]
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
