apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rode.fullname" . }}
  labels:
    app: {{ template "rode.name" . }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.podLabels }}
{{ toYaml . | indent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.podAnnotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rode.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rode.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 65534
      initContainers:
        - name: wait-for-grafeas
          image: curlimages/curl:7.73.0
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-c"
            - |
              until curl --output /dev/null --silent --fail --max-time 2 {{ .Values.grafeasHost }}/v1beta1/projects; do sleep 1; done;
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--port={{ .Values.container.port }}"
            - "--grafeas-host={{ .Values.grafeasHost }}"
            - "--debug={{ .Values.debug }}"
          ports:
            - containerPort: {{ .Values.container.port }}
          {{- with .Values.extraEnv }}
          env:
{{ toYaml . | indent 12 }}
          {{- end }}
          readinessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:{{ .Values.container.port }}"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:{{ .Values.container.port }}"]
            initialDelaySeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
