{{- $fullName := include "rode.name" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $root := .}}
{{- range $ingressType, $ingressConfig := .Values.ingress }}
{{- if $ingressConfig.enabled -}}
{{- if semverCompare ">=1.14-0" $root.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $ingressType }}
  labels:
  {{- include "rode.labels" $root | nindent 4 }}
  {{- with $ingressConfig.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $ingressConfig.tls }}
  tls:
    {{- range $ingressConfig.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    {{- range $ingressConfig.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{- end }}
