replicaCount: 1

image:
  repository: "ghcr.io/rode/collector-tfsec"
  pullPolicy: IfNotPresent
  tag: ""

debug: false

rode:
  host: rode:50051
  insecure: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8083

resources:
  limits:
    cpu: 128m
    memory: 64Mi
  requests:
    cpu: 64m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
