{{- if and .Values.rode.auth.oidc.enabled .Values.rode.auth.basic.enabled }}
  {{ fail "Only one authentication method can be set" }}
{{- end }}
{{- if or .Values.rode.auth.oidc.enabled .Values.rode.auth.basic.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rode-collector-sonarqube.fullname" . }}-auth
  labels:
    {{- include "rode-collector-sonarqube.labels" . | nindent 4 }}
stringData:
  {{- if .Values.rode.auth.oidc.enabled }}
  OIDC_CLIENT_ID: "{{ .Values.rode.auth.oidc.clientId }}"
  OIDC_CLIENT_SECRET: "{{ .Values.rode.auth.oidc.clientSecret }}"
  OIDC_TOKEN_URL: "{{ .Values.rode.auth.oidc.tokenUrl }}"
  OIDC_TLS_INSECURE_SKIP_VERIFY: "{{ .Values.rode.auth.oidc.tlsInsecureSkipVerify }}"
  {{- end }}
  {{- if .Values.rode.auth.basic.enabled }}
  BASIC_AUTH_USERNAME: "{{ .Values.rode.auth.basic.username }}"
  BASIC_AUTH_PASSWORD: "{{ .Values.rode.auth.basic.password }}"
  {{- end }}
{{- end }}
