replicaCount: 1

image:
  repository: "ghcr.io/rode/collector-image-scanner"
  pullPolicy: IfNotPresent
  tag: ""

trivy:
  port: 4954
  image:
    repository: ghcr.io/aquasecurity/trivy
    tag: 0.19.2

debug: false

rode:
  host: rode:50051

  ## disableTransportSecurity will disable GRPC transport security when set to `true`
  ##
  disableTransportSecurity: false

  ## Rode authentication settings
  ## Use rode.auth.proxy.enabled to enable proxy auth
  ##
  auth:
    proxy:
      enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8084

ingress:
  enabled: false
  annotations: {}
  hosts: []
#    - host: chart-example.local
#      paths: []
  tls: []

resources:
  limits:
    cpu: 128m
    memory: 64Mi
  requests:
    cpu: 64m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
