{{- if .Values.rode.auth.oidc.enabled }}
{{- $appSecret := .Values.rode.auth.appSecret | default uuidv4 }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "rode-ui.authSecretName" .)) }}
{{- if $secret }}
{{- $appSecret = index $secret.data "APP_SECRET" | b64dec }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rode-ui.authSecretName" . }}
  labels:
    {{- include "rode-ui.labels" . | nindent 4 }}
stringData:
  OIDC_ENABLED: "true"
  OIDC_CLIENT_ID: "{{ .Values.rode.auth.oidc.clientId }}"
  OIDC_CLIENT_SECRET: "{{ .Values.rode.auth.oidc.clientSecret }}"
  OIDC_ISSUER_URL: "{{ .Values.rode.auth.oidc.issuerUrl }}"
  APP_SECRET: "{{ $appSecret }}"
{{- end }}
