replicaCount: 1

image:
  repository: "ghcr.io/rode/enforcer-k8s"
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

  # rbac.imagePullSecretNames can be used to restrict the enforcer's cluster-wide access to secrets to a particular list of names
#  imagePullSecretNames:
#    - harbor

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

rode:
  host: rode:50051

  ## disableTransportSecurity will disable GRPC transport security when set to `true`
  ##
  disableTransportSecurity: false

  ## Rode authentication settings
  ## Use rode.auth.oidc.enabled to enable OIDC auth
  ## Use rode.auth.basic.enabled to enable basic auth
  ##
  auth:
    oidc:
      enabled: false
      clientId: ""
      clientSecret: ""
      tokenUrl: ""
      tlsInsecureSkipVerify: false
      # scopes is a space delimited list of scopes to request when retrieving an access token
      #
      scopes: ""
    basic:
      enabled: false
      username: ""
      password: ""

  ## policyGroup (required) is the name of the policy group that docker images should be evaluated against
  ##
  policyGroup: ""

debug: false

registryInsecureSkipVerify: false
tlsSecretName: enforcer-k8s
namespaceLabel: enforcer-k8s
kubernetes:
  inCluster: true
  configFile: ""
