apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rode
name: rode
version: 0.1.0
dependencies:
  - name: grafeas-elasticsearch
    repository: https://rode.github.io/charts
    version: 0.0.1
    condition: grafeas.enabled
  - name: opa
    version: 0.1.0-local
    condition: opa.enabled
