apiVersion: v2
description: A Helm chart for rode
name: rode
maintainers:
  - name: Liatrio
    email: rode@liatrio.com
version: 0.0.2
appVersion: 0.0.1
dependencies:
  - name: grafeas-elasticsearch
    repository: https://rode.github.io/charts
    version: 0.0.1
    condition: grafeas.enabled
  - name: opa
    repository: ""
    version: 0.1.0-local
    condition: opa.enabled
