# Default values for rode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rode-ui:
  enabled: true

grafeas-elasticsearch:
  grafeas:
    enabled: true
    container:
      port: 8080
    service:
      port: 8080
    elasticsearch:
      username:
      password:

grafeasHost: "grafeas-server:8080"

opa:
  enabled: true
  host: http://rode-opa:8181

elasticsearch:
  host: http://elasticsearch-master:9200

debug: false

image:
  repository: "ghcr.io/rode/rode"
  tag: "v0.0.5"
  pullPolicy: IfNotPresent

extraEnv: []

container:
  grpcPort: 50051
  httpPort: 50052
service:
  grpc:
    type: ClusterIP
    port: 50051
  http:
    type: ClusterIP
    port: 50052

tolerations: []
affinity: {}
podLabels: {}
nodeSelector: {}
podAnnotations: {}

replicaCount: 1

resources:
  limits:
    cpu: 128m
    memory: 64Mi
  requests:
    cpu: 64m
    memory: 32Mi
