# Default values for rode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rode-ui:
  enabled: true

grafeas-elasticsearch:
  enabled: true
  grafeas:
    container:
      port: 8080
    service:
      port: 8080
    elasticsearch:
      username:
      password:

grafeas:
  host: "grafeas-server:8080"

opa:
  enabled: true
  host: http://rode-opa:8181

elasticsearch:
  host: http://elasticsearch-master:9200

## Rode authentication settings
## Use auth.oidc.enabled to enable OIDC auth
## Use auth.basic.enabled to enable basic auth
##
auth:
  oidc:
    enabled: false
    issuer: ""
    requiredAudience: ""
    roleClaimPath: ""
    tlsInsecureSkipVerify: false
  basic:
    enabled: false
    username: ""
    password: ""

debug: false

image:
  repository: "ghcr.io/rode/rode"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraEnv: []

service:
  type: ClusterIP
  port: 50051

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

replicaCount: 1

resources:
  limits:
    cpu: 128m
    memory: 64Mi
  requests:
    cpu: 64m
    memory: 32Mi
