# Default values for rode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rode-ui:
  enabled: true

grafeas-elasticsearch:
  enabled: true
  grafeas:
    container:
      port: 8080
    service:
      port: 8080
    elasticsearch:
      username:
      password:

grafeas:
  host: "grafeas-server:8080"

opa:
  enabled: true
  host: http://rode-opa:8181

elasticsearch:
  host: http://elasticsearch-master:9200

debug: false

image:
  repository: "ghcr.io/rode/rode"
  pullPolicy: IfNotPresent

extraEnv: []

service:
  type: ClusterIP
  port: 50051

tolerations: []
affinity: {}
podLabels: {}
nodeSelector: {}
podAnnotations: {}

replicaCount: 1

resources:
  limits:
    cpu: 128m
    memory: 64Mi
  requests:
    cpu: 64m
    memory: 32Mi
