# Default values for rode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafeas:
  enabled: true
  container:
    port: 8080
  service:
    port: 8080
  persistence:
    enabled: false
    storageType: memstore

grafeasHost: "grafeas-server:8080"

opa:
  enabled: true

debug: false

image:
  repository: "harbor.toolchain.lead.prod.liatr.io/public/rode"
  tag: ""
  pullPolicy: IfNotPresent

extraEnv: []

container:
  port: 50051
service:
  type: ClusterIP
  port: 50051

tolerations: []
affinity: {}
podLabels: {}
nodeSelector: {}
podAnnotations: {}

replicaCount: 1

resources:
  limits:
    cpu: 128m
    memory: 64Mi
  requests:
    cpu: 64m
    memory: 32Mi
