# Default values for rode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafeas-elasticsearch:
  grafeas:
    enabled: true
    container:
      port: 8080
    service:
      port: 8080
    elasticsearch:
      username:
      password:

grafeasHost: "grafeas-server:8080"

opa:
  enabled: true

debug: false

image:
  repository: "ghcr.io/rode/rode"
  tag: "v0.0.2"
  pullPolicy: IfNotPresent

extraEnv: []

container:
  port: 50051
service:
  type: ClusterIP
  port: 50051

tolerations: []
affinity: {}
podLabels: {}
nodeSelector: {}
podAnnotations: {}

replicaCount: 1

resources:
  limits:
    cpu: 128m
    memory: 64Mi
  requests:
    cpu: 64m
    memory: 32Mi
