grafeas:
  elasticsearch:
    username: "test1234"
    password: "test1234"
elasticsearch:
  replicas: 1
  # Permit co-located instances for single node cluster.
  antiAffinity: "soft"
  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"
  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"
  # Request smaller persistent volumes.
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 10M
