apiVersion: v2
name: grafeas-elasticsearch
description: Grafeas with Elasticsearch backend
type: application
maintainers:
  - name: Liatrio
    email: rode@liatrio.com
version: 0.0.8
appVersion: 0.4.0
dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 7.10.1
    condition: elasticsearch.enabled
