certificates:
  ca: |-
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  cert: |-
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  enabled: false
  key: |-
    -----BEGIN RSA PRIVATE KEY-----
    ...
    -----END RSA PRIVATE KEY-----
  name: grafeas-ssl-certs
container:
  port: 8080
elasticsearch:
  enabled: true
  extraInitContainers:
    - command:
        - sh
        - -c
        - |
          #!/usr/bin/env bash
          bin/elasticsearch-users useradd $GRAFEAS_USERNAME -p $GRAFEAS_PASSWORD
      env:
        - name: GRAFEAS_USERNAME
          valueFrom:
            secretKeyRef:
              key: grafeas_username
              name: elastic-credentials
        - name: GRAFEAS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: grafeas_password
              name: elastic-credentials
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
      imagePullPolicy: IfNotPresent
      name: initialize-auth
fullnameOverride: grafeas-server
grafeas:
  elasticsearch:
    password: null
    refresh: "true"
    url: http://elasticsearch-master:9200
    username: null
image:
  name: grafeas-elasticsearch
  pullPolicy: IfNotPresent
  repository: ghcr.io/rode
  tag: v0.0.0-helm10
livenessprobe:
  failureThreshold: 3
  initialDelaySeconds: 15
  periodSeconds: 10
nameOverride: grafeas-server
readinessprobe:
  failureThreshold: 3
  initialDelaySeconds: 15
  periodSeconds: 10
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
secret:
  enabled: false
service:
  port: 8080
  type: ClusterIP
