{{- if .Values.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificates.name }}
  labels:
    app: {{ template "grafeas.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.crt: {{ .Values.certificates.ca | b64enc }}
  server.crt : {{ .Values.certificates.cert | b64enc }}
  server.key: {{ .Values.certificates.key | b64enc }}
{{- end }}
