apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enforcer-k8s.fullname" . }}
  labels:
    {{- include "enforcer-k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "enforcer-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "enforcer-k8s.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "enforcer-k8s.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" ($.Chart.AppVersion)) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.rode.auth.oidc.enabled .Values.rode.auth.basic.enabled }}
          envFrom:
            - secretRef:
                name: {{ include "enforcer-k8s.fullname" . }}-auth
          {{- end }}
          args:
            - "--port={{ .Values.service.port }}"
            - "--debug={{ .Values.debug }}"
            - "--tls-secret={{ .Release.Namespace }}/{{ .Values.tlsSecretName }}"
            - "--policy-group={{ .Values.rode.policyGroup }}"
            - "--rode-host={{ .Values.rode.host }}"
            - "--rode-insecure-disable-transport-security={{ .Values.rode.disableTransportSecurity }}"
            - "--registry-insecure-skip-verify={{ .Values.registryInsecureSkipVerify }}"
            - "--k8s-in-cluster={{ .Values.kubernetes.inCluster }}"
            {{- if .Values.kubernetes.configFile }}
              {{- if .Values.kubernetes.inCluster }}
                {{- fail "Setting both kubernetes.configFile and kubernetes.inCluster is invalid, use one or the other" }}
              {{- end }}
            - "--k8s-config-file={{ .Values.kubernetes.configFile }}"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
