{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enforcer-k8s.serviceAccountName" . }}
  labels:
    {{- include "enforcer-k8s.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
# necessary in order to read the secret containing the TLS config and any image pull secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "enforcer-k8s.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "enforcer-k8s.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "enforcer-k8s.serviceAccountName" . }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "enforcer-k8s.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
